###
 # (C) Copyright 2013 Faraday Technology
 # BingYao Luo <bjluo@faraday-tech.com>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 ##

export TOP_DIR ?= $(shell pwd)

include config.mk

LDFLAGS += -Ttext 0x00000000

# Move data section to memory, text section
# remain at flash
ifeq ($(IMAGE), RAM)
LDSFILE := ram.lds
else #ROM
ifeq ($(COPYSECT), data)
LDSFILE := rom.lds
else
LDSFILE := ram.lds
endif
endif

ELFNAME := bin/$(IMAGE)-nonos-$(COPYSECT)-$(PLATFORM)-$(shell date +'%C%y%m%d')

dirs-y := lib board cpu drivers app
objs-y := app/app.a drivers/drivers.a board/board.a lib/libgen.a lib/libm.a lib/libc.a cpu/cpu.a

.PHONY: all
all: print version config $(dirs-y) $(ELFNAME).elf

.PHONY: print
print:
	@echo "Build directory: $(dirs-y)"
	@echo "Dependancy objects: $(objs-y)"

.PHONY: version
version:
	@rm -f include/version.h
	@echo "/**" >> include/version.h
	@echo " * This file generated by Makefile." >> include/version.h
	@echo " * Do not modify this file directly." >> include/version.h
	@echo " */" >> include/version.h
	@echo "" >> include/version.h
	@date +'#define PRINT_IMG_VERS " Platform: $(PLATFORM) Type: $(IMAGE) (%C%y.%m.%d-%T)"' >> include/version.h
	@echo "" >> include/version.h

config: config.mk
	@echo "Configuration changes, make clean ... "
	@make clean
	@cd include && ln -sf platform_$(PLATFORM).h platform.h
	@touch config

.PHONY: $(dirs-y)
$(dirs-y):
	@make -C $@ all

$(ELFNAME).elf: start.o $(objs-y)
	$(LD) -Bstatic \
		-T $(LDSFILE) \
		start.o \
		--start-group \
		$(objs-y) -lgcc \
		--end-group \
		$(LDFLAGS) \
		-L $(shell dirname `$(CC) $(CFLAGS) -print-libgcc-file-name`) \
		-Map $(ELFNAME).map -o $(ELFNAME).elf
	$(OBJCOPY) -O binary  $(ELFNAME).elf $(ELFNAME).bin
	$(OD) -D  $(ELFNAME).elf > $(ELFNAME).dump

.PHONY:clean
clean:
	@find -L ./ -name '*.[oa]' | xargs rm -rf

.PHONY : distclean
distclean:
	find -L ./ -name "Makefile.depend" | xargs rm -f
	find -L ./ -name "*.o" -o -name "*.a" -o -name ".*.swp" -o -name "*.map" -o -name "*.elf" \
	-o -name "*.bin" -o -name "*.dump" | xargs rm -f
