###
 # (C) Copyright 2013 Faraday Technology
 # BingYao Luo <bjluo@faraday-tech.com>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 ##

drvobjs-$(CONFIG_FTSPI020) += $(addprefix ftspi020/, cmd_ftspi020.o ftspi020_mxic.o ftspi020_sst.o \
			      ftspi020_cntr.o ftspi020_spansion.o ftspi020_winbond.o ftspi020_nand.o random.o)

drvobjs-$(CONFIG_FTDMAC020) += $(addprefix ftspi020/, ftspi020_dma.o)
drvobjs-$(CONFIG_FTDMAC030) += $(addprefix ftspi020/, ftspi020_dmac030.o)
